appname = RinconesLlaneros_MID
httpport = 8085
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = 



API_CRUD_Usuarios = localhost:8081

host_api = http://localhost:8080/v1/




