appname = RinconesLlaneros_MID
httpport = 8084
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = 

Servicio_Usuarios = http://localhost:8082/v1/Usuarios
Servicio_Credenciales = http://localhost:8082/v1/Credenciales 