appname = RinconesLlaneros_MID
httpport = 8086
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = 




host_api = http://localhost:8080/v1/
Servicio_Usuarios = http://localhost:8080/v1/Usuarios
Servicio_Credenciales = http://localhost:8080/v1/Credenciales 
